### ISSUE TITLE
Forward references from front matter.md blow something up

### ISSUE THREAD

**Issue by JonathanBeverley** [BenGardiner/mindmup-as-attack-trees#10]
My markdown had a line like
* *Mitigation: blah blah blah (*)* 

Causes some sort of python failure, producing the following:
> /usr/lib/python2.7/re.py(155)sub()
    154     a replacement string to be used."""
--> 155     return _compile(pattern, flags).sub(repl, string, count)
    156

ipdb>

Note that this gets dumped into the output file, not enabling debugging.

**Comment by BenGardiner** [comment]
I'm pretty sure I fixed this
